
export const SUPABASE_URL = 'https://tppghsndtbdsdgolpbbh.supabase.co';
export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwcGdoc25kdGJkc2Rnb2xwYmJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMDE4MTAsImV4cCI6MjA2Nzc3NzgxMH0.gOa_df0VrCWHHunbOUuFNh7PESwrIWHTaCG2jEs9U9Y';
